services:
  tap:
    image: ghcr.io/bluesky-social/indigo/tap:latest
    platform: linux/amd64
    ports:
      - "2480:2480"
    environment:
      - TAP_ADMIN_PASSWORD=${TAP_ADMIN_PASSWORD:-y29d6b572f17af0f150cd4b480bec85cf}
      - TAP_COLLECTION_FILTERS=xyz.opnshelf.*
    volumes:
      - tap-data:/data
    depends_on:
      - opnshelf-postgres

  opnshelf-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: opnshelf
      POSTGRES_PASSWORD: opnshelf
      POSTGRES_DB: opnshelf
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  tap-data:
  postgres-data:
