packages:
  - apps/*
  - packages/*
  - backend
overrides:
  '@tanstack/query-core': 5.100.14
  '@tanstack/react-query': 5.100.14
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  canvas: true
  core-js: true
  esbuild: true
  prisma: true
  protobufjs: true
  lightningcss: true
  unrs-resolver: true
  msgpackr-extract: false
