packages:
  - apps/*
  - packages/*
  - backend

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - canvas
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - unrs-resolver
