/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'xyz.opnshelf.core'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', {
      collection: [
        'xyz.opnshelf.movie',
        'xyz.opnshelf.episode',
        'xyz.opnshelf.list',
        'xyz.opnshelf.list.item',
        'xyz.opnshelf.library.item',
        'xyz.opnshelf.follow',
        'xyz.opnshelf.profile',
        'xyz.opnshelf.note',
        'xyz.opnshelf.review',
        'xyz.opnshelf.review.like',
        'xyz.opnshelf.rating',
      ],
    }),
  ],
  {
    title: 'Core Opnshelf Access',
    detail: 'Create, update, and delete your Opnshelf records.',
  },
)

export { main }
