/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'xyz.opnshelf.list'

export { $nsid }

/** A movie list for Opnshelf */
type Main = {
  $type: 'xyz.opnshelf.list'

  /**
   * Display name of the list
   */
  name: string

  /**
   * Optional description of the list
   */
  description?: string

  /**
   * URL-friendly identifier
   */
  slug: string

  /**
   * Whether this is a default list (watchlist/favorites)
   */
  isDefault: boolean

  /**
   * Record creation timestamp
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A movie list for Opnshelf */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    name: l.string(),
    description: l.optional(l.string()),
    slug: l.string(),
    isDefault: l.boolean(),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
