/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'xyz.opnshelf.listItem'

export { $nsid }

/** A media item in a list for OpnShelf */
type Main = {
  $type: 'xyz.opnshelf.listItem'

  /**
   * Rkey of the parent list
   */
  listRkey: string

  /**
   * Media type
   */
  mediaType: 'movie' | 'show'

  /**
   * TMDB media ID
   */
  mediaId: string

  /**
   * Optional user notes about the media in this list
   */
  notes?: string

  /**
   * Record creation timestamp
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A media item in a list for OpnShelf */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    listRkey: l.string(),
    mediaType: l.enum(['movie', 'show']),
    mediaId: l.string(),
    notes: l.optional(l.string()),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
