/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'xyz.opnshelf.mediaLink'

export { $nsid }

/** An embedded, typed link binding a standard.site document to an OpnShelf media item. Placed inside a document's open `links` union; gets no collection and no record of its own. */
type Main = {
  $type?: 'xyz.opnshelf.mediaLink'

  /**
   * Media type
   */
  mediaType: 'movie' | 'show' | 'season' | 'episode'

  /**
   * TMDB movie ID or show ID
   */
  mediaId: string

  /**
   * Season number for season/episode items
   */
  seasonNumber?: number

  /**
   * Episode number for episode items
   */
  episodeNumber?: number
}

export type { Main }

/** An embedded, typed link binding a standard.site document to an OpnShelf media item. Placed inside a document's open `links` union; gets no collection and no record of its own. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    mediaType: l.enum(['movie', 'show', 'season', 'episode']),
    mediaId: l.string(),
    seasonNumber: l.optional(l.integer()),
    episodeNumber: l.optional(l.integer()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
