/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'xyz.opnshelf.note'

export { $nsid }

/** A user note about a media item */
type Main = {
  $type: 'xyz.opnshelf.note'

  /**
   * Media type
   */
  mediaType: 'movie' | 'show' | 'season' | 'episode'

  /**
   * TMDB movie ID or show ID
   */
  mediaId: string

  /**
   * Season number for season/episode items
   */
  seasonNumber?: number

  /**
   * Episode number for episode items
   */
  episodeNumber?: number

  /**
   * Note content
   */
  content: string

  /**
   * Record creation timestamp
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A user note about a media item */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    mediaType: l.enum(['movie', 'show', 'season', 'episode']),
    mediaId: l.string(),
    seasonNumber: l.optional(l.integer()),
    episodeNumber: l.optional(l.integer()),
    content: l.string({ maxLength: 5000 }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
