/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'xyz.opnshelf.profile'

export { $nsid }

/** An Opnshelf profile record */
type Main = {
  $type: 'xyz.opnshelf.profile'

  /**
   * Display name shown in Opnshelf
   */
  displayName?: string

  /**
   * Profile photo stored in the user's PDS
   */
  avatar?: l.BlobRef

  /**
   * Record creation timestamp
   */
  createdAt: l.DatetimeString

  /**
   * Record update timestamp
   */
  updatedAt: l.DatetimeString
}

export type { Main }

/** An Opnshelf profile record */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    displayName: l.optional(l.string({ maxLength: 64 })),
    avatar: l.optional(
      l.blob({
        accept: ['image/jpeg', 'image/png', 'image/webp'],
        maxSize: 5242880,
        allowLegacy: false,
      }),
    ),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
