/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as ListsListSlugRouteImport } from './routes/lists.$listSlug'
import { Route as AuthCompleteRouteImport } from './routes/auth/complete'
import { Route as ShowsShowIdShowNameRouteImport } from './routes/shows/$showId/$showName'
import { Route as MoviesMovieIdMovieNameRouteImport } from './routes/movies/$movieId/$movieName'
import { Route as ShowsShowIdShowNameIndexRouteImport } from './routes/shows/$showId/$showName/index'
import { Route as ShowsShowIdShowNameSeasonsSeasonNumberRouteImport } from './routes/shows/$showId/$showName/seasons.$seasonNumber'
import { Route as ShowsShowIdShowNameSeasonsSeasonNumberIndexRouteImport } from './routes/shows/$showId/$showName/seasons.$seasonNumber/index'
import { Route as ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRouteImport } from './routes/shows/$showId/$showName/seasons.$seasonNumber.episodes.$episodeNumber'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const ListsListSlugRoute = ListsListSlugRouteImport.update({
  id: '/$listSlug',
  path: '/$listSlug',
  getParentRoute: () => ListsRoute,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdShowNameRoute = ShowsShowIdShowNameRouteImport.update({
  id: '/shows/$showId/$showName',
  path: '/shows/$showId/$showName',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdMovieNameRoute = MoviesMovieIdMovieNameRouteImport.update({
  id: '/movies/$movieId/$movieName',
  path: '/movies/$movieId/$movieName',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdShowNameIndexRoute =
  ShowsShowIdShowNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShowsShowIdShowNameRoute,
  } as any)
const ShowsShowIdShowNameSeasonsSeasonNumberRoute =
  ShowsShowIdShowNameSeasonsSeasonNumberRouteImport.update({
    id: '/seasons/$seasonNumber',
    path: '/seasons/$seasonNumber',
    getParentRoute: () => ShowsShowIdShowNameRoute,
  } as any)
const ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute =
  ShowsShowIdShowNameSeasonsSeasonNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShowsShowIdShowNameSeasonsSeasonNumberRoute,
  } as any)
const ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute =
  ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRouteImport.update(
    {
      id: '/episodes/$episodeNumber',
      path: '/episodes/$episodeNumber',
      getParentRoute: () => ShowsShowIdShowNameSeasonsSeasonNumberRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/following': typeof FollowingRoute
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/lists/$listSlug': typeof ListsListSlugRoute
  '/lists/': typeof ListsIndexRoute
  '/movies/$movieId/$movieName': typeof MoviesMovieIdMovieNameRoute
  '/shows/$showId/$showName': typeof ShowsShowIdShowNameRouteWithChildren
  '/shows/$showId/$showName/': typeof ShowsShowIdShowNameIndexRoute
  '/shows/$showId/$showName/seasons/$seasonNumber': typeof ShowsShowIdShowNameSeasonsSeasonNumberRouteWithChildren
  '/shows/$showId/$showName/seasons/$seasonNumber/': typeof ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute
  '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber': typeof ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/lists/$listSlug': typeof ListsListSlugRoute
  '/lists': typeof ListsIndexRoute
  '/movies/$movieId/$movieName': typeof MoviesMovieIdMovieNameRoute
  '/shows/$showId/$showName': typeof ShowsShowIdShowNameIndexRoute
  '/shows/$showId/$showName/seasons/$seasonNumber': typeof ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute
  '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber': typeof ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/following': typeof FollowingRoute
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/lists/$listSlug': typeof ListsListSlugRoute
  '/lists/': typeof ListsIndexRoute
  '/movies/$movieId/$movieName': typeof MoviesMovieIdMovieNameRoute
  '/shows/$showId/$showName': typeof ShowsShowIdShowNameRouteWithChildren
  '/shows/$showId/$showName/': typeof ShowsShowIdShowNameIndexRoute
  '/shows/$showId/$showName/seasons/$seasonNumber': typeof ShowsShowIdShowNameSeasonsSeasonNumberRouteWithChildren
  '/shows/$showId/$showName/seasons/$seasonNumber/': typeof ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute
  '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber': typeof ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/dashboard'
    | '/following'
    | '/lists'
    | '/login'
    | '/auth/complete'
    | '/lists/$listSlug'
    | '/lists/'
    | '/movies/$movieId/$movieName'
    | '/shows/$showId/$showName'
    | '/shows/$showId/$showName/'
    | '/shows/$showId/$showName/seasons/$seasonNumber'
    | '/shows/$showId/$showName/seasons/$seasonNumber/'
    | '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/dashboard'
    | '/following'
    | '/login'
    | '/auth/complete'
    | '/lists/$listSlug'
    | '/lists'
    | '/movies/$movieId/$movieName'
    | '/shows/$showId/$showName'
    | '/shows/$showId/$showName/seasons/$seasonNumber'
    | '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/dashboard'
    | '/following'
    | '/lists'
    | '/login'
    | '/auth/complete'
    | '/lists/$listSlug'
    | '/lists/'
    | '/movies/$movieId/$movieName'
    | '/shows/$showId/$showName'
    | '/shows/$showId/$showName/'
    | '/shows/$showId/$showName/seasons/$seasonNumber'
    | '/shows/$showId/$showName/seasons/$seasonNumber/'
    | '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  FollowingRoute: typeof FollowingRoute
  ListsRoute: typeof ListsRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  MoviesMovieIdMovieNameRoute: typeof MoviesMovieIdMovieNameRoute
  ShowsShowIdShowNameRoute: typeof ShowsShowIdShowNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/lists/$listSlug': {
      id: '/lists/$listSlug'
      path: '/$listSlug'
      fullPath: '/lists/$listSlug'
      preLoaderRoute: typeof ListsListSlugRouteImport
      parentRoute: typeof ListsRoute
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId/$showName': {
      id: '/shows/$showId/$showName'
      path: '/shows/$showId/$showName'
      fullPath: '/shows/$showId/$showName'
      preLoaderRoute: typeof ShowsShowIdShowNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId/$movieName': {
      id: '/movies/$movieId/$movieName'
      path: '/movies/$movieId/$movieName'
      fullPath: '/movies/$movieId/$movieName'
      preLoaderRoute: typeof MoviesMovieIdMovieNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId/$showName/': {
      id: '/shows/$showId/$showName/'
      path: '/'
      fullPath: '/shows/$showId/$showName/'
      preLoaderRoute: typeof ShowsShowIdShowNameIndexRouteImport
      parentRoute: typeof ShowsShowIdShowNameRoute
    }
    '/shows/$showId/$showName/seasons/$seasonNumber': {
      id: '/shows/$showId/$showName/seasons/$seasonNumber'
      path: '/seasons/$seasonNumber'
      fullPath: '/shows/$showId/$showName/seasons/$seasonNumber'
      preLoaderRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberRouteImport
      parentRoute: typeof ShowsShowIdShowNameRoute
    }
    '/shows/$showId/$showName/seasons/$seasonNumber/': {
      id: '/shows/$showId/$showName/seasons/$seasonNumber/'
      path: '/'
      fullPath: '/shows/$showId/$showName/seasons/$seasonNumber/'
      preLoaderRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberIndexRouteImport
      parentRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberRoute
    }
    '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber': {
      id: '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber'
      path: '/episodes/$episodeNumber'
      fullPath: '/shows/$showId/$showName/seasons/$seasonNumber/episodes/$episodeNumber'
      preLoaderRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRouteImport
      parentRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberRoute
    }
  }
}

interface ListsRouteChildren {
  ListsListSlugRoute: typeof ListsListSlugRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListSlugRoute: ListsListSlugRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

interface ShowsShowIdShowNameSeasonsSeasonNumberRouteChildren {
  ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute
  ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute
}

const ShowsShowIdShowNameSeasonsSeasonNumberRouteChildren: ShowsShowIdShowNameSeasonsSeasonNumberRouteChildren =
  {
    ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute:
      ShowsShowIdShowNameSeasonsSeasonNumberIndexRoute,
    ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute:
      ShowsShowIdShowNameSeasonsSeasonNumberEpisodesEpisodeNumberRoute,
  }

const ShowsShowIdShowNameSeasonsSeasonNumberRouteWithChildren =
  ShowsShowIdShowNameSeasonsSeasonNumberRoute._addFileChildren(
    ShowsShowIdShowNameSeasonsSeasonNumberRouteChildren,
  )

interface ShowsShowIdShowNameRouteChildren {
  ShowsShowIdShowNameIndexRoute: typeof ShowsShowIdShowNameIndexRoute
  ShowsShowIdShowNameSeasonsSeasonNumberRoute: typeof ShowsShowIdShowNameSeasonsSeasonNumberRouteWithChildren
}

const ShowsShowIdShowNameRouteChildren: ShowsShowIdShowNameRouteChildren = {
  ShowsShowIdShowNameIndexRoute: ShowsShowIdShowNameIndexRoute,
  ShowsShowIdShowNameSeasonsSeasonNumberRoute:
    ShowsShowIdShowNameSeasonsSeasonNumberRouteWithChildren,
}

const ShowsShowIdShowNameRouteWithChildren =
  ShowsShowIdShowNameRoute._addFileChildren(ShowsShowIdShowNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  FollowingRoute: FollowingRoute,
  ListsRoute: ListsRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  MoviesMovieIdMovieNameRoute: MoviesMovieIdMovieNameRoute,
  ShowsShowIdShowNameRoute: ShowsShowIdShowNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
