/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.opnshelf.episode'

export { $nsid }

/** A tracked show episode record for OpnShelf */
type Main = {
  $type: 'app.opnshelf.episode'

  /**
   * TMDB show ID
   */
  showId: string

  /**
   * TMDB season number
   */
  seasonNumber: number

  /**
   * TMDB episode number
   */
  episodeNumber: number

  /**
   * Source of the show data (e.g., tmdb)
   */
  source: string

  /**
   * When the episode was watched
   */
  watchedAt: l.DatetimeString

  /**
   * Record creation timestamp
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A tracked show episode record for OpnShelf */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    showId: l.string(),
    seasonNumber: l.integer(),
    episodeNumber: l.integer(),
    source: l.string(),
    watchedAt: l.string({ format: 'datetime' }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
