/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex';

const $nsid = 'app.opnshelf.movie';

export { $nsid };

/** A tracked movie record for OpnShelf */
type Main = {
  $type: 'app.opnshelf.movie';

  /**
   * TMDB movie ID
   */
  movieId: string;

  /**
   * Source of the movie data (e.g., tmdb)
   */
  source: string;

  /**
   * When the movie was watched
   */
  watchedAt: l.DatetimeString;

  /**
   * Record creation timestamp
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A tracked movie record for OpnShelf */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    movieId: l.string(),
    source: l.string(),
    watchedAt: l.string({ format: 'datetime' }),
    createdAt: l.string({ format: 'datetime' }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
