/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as MarkpubMarkdown from '../../at/markpub/markdown.defs.js'
import * as OpnshelfMediaLink from '../../xyz/opnshelf/mediaLink.defs.js'

const $nsid = 'site.standard.document'

export { $nsid }

/** Metadata for an individual long-form document published to the web. Vendored subset of site.standard.document. */
type Main = {
  $type: 'site.standard.document'

  /**
   * AT-URI of the site.standard.publication this document belongs to
   */
  site: l.AtUriString

  /**
   * Document title
   */
  title: string

  /**
   * URL path segment for the document on the publication
   */
  path?: string

  /**
   * Short plaintext excerpt for cross-tool preview
   */
  description?: string

  /**
   * Plaintext rendering of the body for cross-tool preview (must not contain markdown)
   */
  textContent?: string

  /**
   * Optional cover image blob
   */
  coverImage?: l.BlobRef

  /**
   * Open content union; opnshelf reviews carry an at.markpub.markdown member
   */
  content?: l.$Typed<MarkpubMarkdown.Main> | l.Unknown$TypedObject

  /**
   * Open links union; opnshelf reviews carry an xyz.opnshelf.mediaLink member binding the document to a media item
   */
  links?: l.$Typed<OpnshelfMediaLink.Main> | l.Unknown$TypedObject

  /**
   * Publication timestamp
   */
  publishedAt: l.DatetimeString

  /**
   * Last edit timestamp
   */
  updatedAt?: l.DatetimeString
}

export type { Main }

/** Metadata for an individual long-form document published to the web. Vendored subset of site.standard.document. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    site: l.string({ format: 'at-uri' }),
    title: l.string(),
    path: l.optional(l.string()),
    description: l.optional(l.string()),
    textContent: l.optional(l.string()),
    coverImage: l.optional(
      l.blob({ accept: ['image/*'], maxSize: 1000000, allowLegacy: false }),
    ),
    content: l.optional(
      l.typedUnion(
        [l.typedRef<MarkpubMarkdown.Main>((() => MarkpubMarkdown.main) as any)],
        false,
      ),
    ),
    links: l.optional(
      l.typedUnion(
        [
          l.typedRef<OpnshelfMediaLink.Main>(
            (() => OpnshelfMediaLink.main) as any,
          ),
        ],
        false,
      ),
    ),
    publishedAt: l.string({ format: 'datetime' }),
    updatedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
