/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'site.standard.publication'

export { $nsid }

/** A representation of a collection of documents published to the web. Vendored subset of site.standard.publication. */
type Main = {
  $type: 'site.standard.publication'

  /**
   * Canonical web URL of the publication
   */
  url: l.UriString

  /**
   * Display name of the publication
   */
  name: string

  /**
   * Optional description of the publication
   */
  description?: string
}

export type { Main }

/** A representation of a collection of documents published to the web. Vendored subset of site.standard.publication. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    url: l.string({ format: 'uri' }),
    name: l.string(),
    description: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
