/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * as episode from './opnshelf/episode.js'
export * as follow from './opnshelf/follow.js'
export * as list from './opnshelf/list.js'
export * as movie from './opnshelf/movie.js'
export * as note from './opnshelf/note.js'
export * as profile from './opnshelf/profile.js'
export * as rating from './opnshelf/rating.js'
export * as review from './opnshelf/review.js'
