/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as MarkpubText from './text.defs.js'

const $nsid = 'at.markpub.markdown'

export { $nsid }

/** A markdown content object intended to be embedded inside other records (e.g. a standard.site document's open `content` union). Vendored subset of at.markpub.markdown. */
type Main = {
  $type?: 'at.markpub.markdown'

  /**
   * An object that includes the text in markdown
   */
  text: MarkpubText.Main

  /**
   * Markdown rendering flavor
   */
  flavor?: 'gfm' | 'commonmark' | l.UnknownString
}

export type { Main }

/** A markdown content object intended to be embedded inside other records (e.g. a standard.site document's open `content` union). Vendored subset of at.markpub.markdown. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    text: l.ref<MarkpubText.Main>((() => MarkpubText.main) as any),
    flavor: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
