/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'at.markpub.text'

export { $nsid }

/** A markpub text object carrying raw markdown (vendored subset). */
type Main = {
  $type?: 'at.markpub.text'

  /**
   * Raw text in markdown
   */
  markdown: string

  /**
   * Optional blob reference overriding the inline markdown string
   */
  textBlob?: l.BlobRef
}

export type { Main }

/** A markpub text object carrying raw markdown (vendored subset). */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    markdown: l.string(),
    textBlob: l.optional(
      l.blob({ maxSize: 1000000, accept: ['text/*'], allowLegacy: false }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
