export const COUNTRY_NAMES: Record<string, string> = {
	AR: "Argentina",
	AT: "Austria",
	AU: "Australia",
	BE: "Belgium",
	BR: "Brazil",
	CA: "Canada",
	CH: "Switzerland",
	CL: "Chile",
	CO: "Colombia",
	DE: "Germany",
	DK: "Denmark",
	ES: "Spain",
	FI: "Finland",
	FR: "France",
	GB: "United Kingdom",
	HK: "Hong Kong",
	ID: "Indonesia",
	IN: "India",
	IT: "Italy",
	JP: "Japan",
	KR: "South Korea",
	MX: "Mexico",
	MY: "Malaysia",
	NL: "Netherlands",
	NO: "Norway",
	NZ: "New Zealand",
	PH: "Philippines",
	PL: "Poland",
	PT: "Portugal",
	SE: "Sweden",
	SG: "Singapore",
	TH: "Thailand",
	TR: "Turkey",
	US: "United States",
	ZA: "South Africa",
};

export const SORTED_COUNTRIES = Object.entries(COUNTRY_NAMES).sort(
	([, a], [, b]) => a.localeCompare(b),
);
